%-----------------------------------------------------------------------
% Job saved on 24-Apr-2023 20:41:56 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.stats.fmri_spec.dir = {'/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold'};
matlabbatch{1}.spm.stats.fmri_spec.timing.units = 'secs';
matlabbatch{1}.spm.stats.fmri_spec.timing.RT = 2.4;
matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t = 40;
matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t0 = 20;
%%
matlabbatch{1}.spm.stats.fmri_spec.sess.scans = {
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_001.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_128.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_002.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_003.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_004.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_005.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_006.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_007.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_008.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_009.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_010.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_011.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_012.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_013.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_014.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_015.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_016.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_017.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_018.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_019.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_020.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_021.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_022.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_023.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_024.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_025.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_026.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_027.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_028.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_029.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_030.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_031.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_032.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_033.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_034.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_035.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_036.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_037.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_038.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_039.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_040.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_041.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_042.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_043.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_044.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_045.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_046.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_047.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_048.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_049.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_050.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_051.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_052.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_053.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_054.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_055.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_056.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_057.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_058.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_059.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_060.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_061.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_062.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_063.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_064.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_065.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_066.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_067.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_068.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_069.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_070.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_071.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_072.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_073.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_074.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_075.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_076.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_077.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_078.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_079.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_080.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_081.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_082.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_083.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_084.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_085.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_086.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_087.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_088.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_089.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_090.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_091.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_092.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_093.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_094.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_095.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_096.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_097.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_098.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_099.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_100.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_101.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_102.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_103.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_104.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_105.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_106.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_107.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_108.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_109.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_110.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_111.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_112.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_113.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_114.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_115.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_116.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_117.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_118.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_119.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_120.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_121.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_122.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_123.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_124.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_125.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_126.img,1'
                                                 '/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/ELEC498_fmri_zero/origin/GH158/bold/swrraGH158_bold_127.img,1'
                                                 };
%%
matlabbatch{1}.spm.stats.fmri_spec.sess.cond = struct('name', {}, 'onset', {}, 'duration', {}, 'tmod', {}, 'pmod', {}, 'orth', {});
matlabbatch{1}.spm.stats.fmri_spec.sess.multi = {'/Users/vincentbeaulieu/Documents/MATLAB/ELEC_445/Final Project/RA-MATLAB/paradigm.mat'};
matlabbatch{1}.spm.stats.fmri_spec.sess.regress = struct('name', {}, 'val', {});
matlabbatch{1}.spm.stats.fmri_spec.sess.multi_reg = {''};
matlabbatch{1}.spm.stats.fmri_spec.sess.hpf = 128;
matlabbatch{1}.spm.stats.fmri_spec.fact = struct('name', {}, 'levels', {});
matlabbatch{1}.spm.stats.fmri_spec.bases.hrf.derivs = [0 0];
matlabbatch{1}.spm.stats.fmri_spec.volt = 1;
matlabbatch{1}.spm.stats.fmri_spec.global = 'None';
matlabbatch{1}.spm.stats.fmri_spec.mthresh = 0.8;
matlabbatch{1}.spm.stats.fmri_spec.mask = {''};
matlabbatch{1}.spm.stats.fmri_spec.cvi = 'AR(1)';
